name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hub
        uses: huggingface/huggingface-action@v0.0.1
        with:
          username: "Prantik-07"
          space: "fraud-detection-dashboard"
          token: ${{ secrets.HF_TOKEN }}
